language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: h-router
  api_key:
    secure: A3UHSDEMNafjZmG6fswQkGLu/Yk0dkylwBnVVXN8PbniXy/LgBElGdkTZOyWXnT07JKFDMRhrAHbsS7BfKperQBPytZvIlcEZpyLZizsKp9yPh0ClTcvfLBLVuFZZ/9snBPNFVcYQToKsOoc4x3YtPc9kCotIEiR+VHN/DK9V8g+EhqL0cRL8ZOYXcL/bGn8NF344AxBpbCmbeJ+iRC7RVe5v77L/cmOnjx3hgH1ogTmKNHP5aCC5uxqQr8vjlDOaGU8BhghqjGQFY9g/WYldAHa/V7ECqb4meW4DhZffxYSciWHCiqmi2Pc1ZcKDxoTLmmwqIlmntNSlhyVw0XwyD0uSAlGoEcIP1VgoxtmQKFxXungpoUV08v/RTMQz9lxboN6J7q7ZTgQZ/5/uWU1ZR1duqN3wLAz97oXFEGwkX7CWc96IcQWtVsRj8gdB6ADyoKpd0Tt/wgI13SyfA5d2vMJGgRvSZIruiub5mqfSLmcPjJ6Fk97/lIg4T9Q4uqbHV8Jljm0AVQuzS+ZHq010lpeKJaW/g9iKZs6FVOZjb4dM6aWPjnJrm17kQAwSlCUsN+2CefB1CtDrcxPA1DNc5R8q+hY7zMwkila7iiczk97osA6uuqgvV6CFqwTdEpgL2J/UeOJi6A3nRNNvNrTR0IzLjX/z2Pakjxi6LQhfw4=
